CREATE DATABASE IF NOT EXISTS nutrifit_db;
USE nutrifit_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  age INT NULL,
  gender VARCHAR(30) NULL,
  height DECIMAL(5,2) NULL,
  weight DECIMAL(5,2) NULL,
  waist DECIMAL(5,2) NULL,
  date_of_birth DATE NULL,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  profile_complete TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  specialty VARCHAR(120) NULL,
  experience_years INT NULL,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  total_ratings INT NOT NULL DEFAULT 0,
  avatar VARCHAR(4) NULL,
  available TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS foods (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NULL,
  diet_type ENUM('veg', 'nonveg') NOT NULL DEFAULT 'veg',
  calories DECIMAL(8,2) NOT NULL,
  protein DECIMAL(8,2) NOT NULL DEFAULT 0,
  carbs DECIMAL(8,2) NOT NULL DEFAULT 0,
  fat DECIMAL(8,2) NOT NULL DEFAULT 0,
  iron DECIMAL(8,2) NOT NULL DEFAULT 0,
  calcium DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_c DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_d DECIMAL(8,2) NOT NULL DEFAULT 0,
  fiber DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_b12 DECIMAL(8,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meals (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  food_id BIGINT UNSIGNED NULL,
  name VARCHAR(120) NOT NULL,
  meal_time VARCHAR(30) NULL,
  calories DECIMAL(8,2) NOT NULL,
  protein DECIMAL(8,2) NOT NULL DEFAULT 0,
  carbs DECIMAL(8,2) NOT NULL DEFAULT 0,
  fat DECIMAL(8,2) NOT NULL DEFAULT 0,
  iron DECIMAL(8,2) NOT NULL DEFAULT 0,
  calcium DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_c DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_d DECIMAL(8,2) NOT NULL DEFAULT 0,
  fiber DECIMAL(8,2) NOT NULL DEFAULT 0,
  vit_b12 DECIMAL(8,2) NOT NULL DEFAULT 0,
  consumed_on DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_meals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_meals_food FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE SET NULL,
  INDEX idx_meals_user_date (user_id, consumed_on)
);

CREATE TABLE IF NOT EXISTS water_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  consumed_on DATE NOT NULL,
  glasses INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_water_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_water_user_date (user_id, consumed_on),
  INDEX idx_water_user_date (user_id, consumed_on)
);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_conversation_pair (user_id, doctor_id),
  CONSTRAINT fk_conv_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_conv_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id BIGINT UNSIGNED NOT NULL,
  sender_type ENUM('user', 'doctor') NOT NULL,
  sender_user_id BIGINT UNSIGNED NULL,
  sender_doctor_id BIGINT UNSIGNED NULL,
  text TEXT NOT NULL,
  rated TINYINT(1) NOT NULL DEFAULT 0,
  rating TINYINT UNSIGNED NULL,
  feedback TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_user_sender FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_messages_doctor_sender FOREIGN KEY (sender_doctor_id) REFERENCES doctors(id) ON DELETE SET NULL,
  INDEX idx_messages_conversation (conversation_id, created_at),
  INDEX idx_messages_doctor_sender (sender_doctor_id)
);
